// <auto-generated />
namespace Tariff.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rate_collections_in_Param_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rate_collections_in_Param_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201911081802213_Rate_collections_in_Param_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
